#!/bin/bash

set -e

print_usage() {
    echo "Usage: $0 <input_file.wav> [--output-file <output_file.wav>]"
    echo ""
    echo "Options:"
    echo "  --output-file    Specify the output filename. Default: <input_filename>_filtered.wav"
    echo "  -h, --help       Print this help message"
}

INPUT_FILE=""
OUTPUT_FILE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --output-file|-o)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            print_usage
            exit 1
            ;;
        *)
            if [[ -z "$INPUT_FILE" ]]; then
                INPUT_FILE="$1"
                shift
            else
                echo "Error: Multiple input files not supported."
                print_usage
                exit 1
            fi
            ;;
    esac
done

if [[ -z "$INPUT_FILE" ]]; then
    echo "Error: No input file specified."
    print_usage
    exit 1
fi

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' does not exist."
    exit 1
fi

# Set default output filename if not provided
if [[ -z "$OUTPUT_FILE" ]]; then
    BASENAME=$(basename "$INPUT_FILE")
    NAME="${BASENAME%.*}"
    EXT="${BASENAME##*.}"
    OUTPUT_FILE="${NAME}_filtered.${EXT}"
fi

# Create a temporary directory for deep-filter output
TMP_DIR=$(mktemp -d)

# Ensure the temp directory is cleaned up on exit
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Processing '$INPUT_FILE' with deep-filter..."

# Run deep-filter
if ! deep-filter -o "$TMP_DIR" "$INPUT_FILE"; then
    echo "Error: deep-filter failed."
    exit 1
fi

# Find the output file generated by deep-filter
# deep-filter preserves the filename, so we look for it in the temp dir
GENERATED_FILE="$TMP_DIR/$(basename "$INPUT_FILE")"

if [[ -f "$GENERATED_FILE" ]]; then
    mv "$GENERATED_FILE" "$OUTPUT_FILE"
    echo "Success! Saved filtered audio to '$OUTPUT_FILE'"
else
    # Fallback in case deep-filter changes the filename format
    FOUND_FILE=$(find "$TMP_DIR" -type f | head -n 1)
    if [[ -n "$FOUND_FILE" ]]; then
        mv "$FOUND_FILE" "$OUTPUT_FILE"
        echo "Success! Saved filtered audio to '$OUTPUT_FILE'"
    else
        echo "Error: deep-filter did not generate an output file."
        exit 1
    fi
fi
